import { Plus, Sparkles, UserRound } from "lucide-react";
import { Button } from "../../components/ui/button";
import type { SessionSummary } from "./types";

type SessionSidebarProps = { sessions: SessionSummary[]; activeSessionId: string | null; onSessionSelect: (sessionId: string) => void; onNewSession: () => void; accountEmail: string; environmentLabel: string; isLoading?: boolean; isNewSessionDisabled?: boolean; errorMessage?: string | null; mobile?: boolean };
type SessionGroupKey = "today" | "yesterday" | "previous-7-days";
const groups: Array<{ key: SessionGroupKey; label: string }> = [{ key: "today", label: "Today" }, { key: "yesterday", label: "Yesterday" }, { key: "previous-7-days", label: "Previous 7 days" }];
function getSessionGroup(updatedAt: string): SessionGroupKey { const date = new Date(updatedAt); if (Number.isNaN(date.getTime())) return "previous-7-days"; const today = new Date(); const todayStart = new Date(today.getFullYear(), today.getMonth(), today.getDate()).getTime(); const updatedStart = new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime(); const days = Math.floor((todayStart - updatedStart) / 86_400_000); return days <= 0 ? "today" : days === 1 ? "yesterday" : "previous-7-days"; }
export function SessionSidebar({ sessions, activeSessionId, onSessionSelect, onNewSession, accountEmail, environmentLabel, isLoading = false, isNewSessionDisabled = false, errorMessage = null, mobile = false }: SessionSidebarProps) {
  const grouped = groups.map((group) => ({ ...group, sessions: sessions.filter((session) => getSessionGroup(session.updatedAt) === group.key).sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()) })).filter((group) => group.sessions.length > 0);
  return <aside className={mobile ? "flex h-full w-full shrink-0 flex-col bg-navy text-white" : "hidden w-[256px] shrink-0 flex-col border-r border-white/10 bg-navy text-white lg:flex"} aria-label="Session sidebar">
    <div className="flex h-16 shrink-0 items-center border-b border-white/10 px-5"><div className="flex items-center gap-2.5"><div className="flex h-8 w-8 items-center justify-center rounded-[10px] bg-accent text-navy shadow-sm" aria-hidden="true"><Sparkles size={16} strokeWidth={2.3} /></div><span className="text-[15px] font-bold tracking-[-0.02em]">opspilot</span></div></div>
    <div className="px-4 pt-5"><Button variant="primary" size="md" className="w-full justify-start bg-accent/95" onClick={onNewSession} disabled={isNewSessionDisabled} aria-label="Start a new session"><Plus size={17} strokeWidth={2.4} aria-hidden="true" />{isNewSessionDisabled && !isLoading ? "Creating..." : "New session"}</Button></div>
    <nav className="min-h-0 flex-1 overflow-y-auto px-3 py-6" aria-label="Session history"><p className="px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.14em] text-navy-muted/75">Session history</p>{isLoading ? <p className="px-3 text-xs text-navy-muted" role="status">Loading sessions...</p> : errorMessage ? <p className="px-3 text-xs leading-5 text-[#f6b8ad]" role="alert">{errorMessage}</p> : grouped.length === 0 ? <p className="px-3 text-xs leading-5 text-navy-muted">No sessions yet. Start a new one to begin.</p> : <div className="space-y-5">{grouped.map((group) => <section key={group.key} aria-labelledby={`session-group-${group.key}`}><h2 id={`session-group-${group.key}`} className="px-3 pb-1.5 text-[10px] font-semibold uppercase tracking-[0.14em] text-navy-muted/75">{group.label}</h2><div className="space-y-0.5">{group.sessions.map((session) => { const active = session.id === activeSessionId; return <button key={session.id} type="button" onClick={() => onSessionSelect(session.id)} className={`flex min-h-10 w-full cursor-pointer items-center rounded-lg px-3 text-left text-xs transition duration-200 ease-snappy focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent ${active ? "bg-white/[0.12] font-semibold text-white" : "text-navy-muted hover:bg-white/[0.08] hover:text-white"}`} aria-current={active ? "page" : undefined} title={session.title}><span className="min-w-0 truncate">{session.title}</span></button>; })}</div></section>)}</div>}</nav>
    <div className="shrink-0 border-t border-white/10 p-4"><div className="mb-4 flex items-center gap-2 rounded-lg bg-white/[0.06] px-3 py-2.5"><span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-[#4ade80] opacity-50 motion-reduce:animate-none" /><span className="relative inline-flex h-2 w-2 rounded-full bg-[#4ade80]" /></span><span className="text-xs text-navy-muted">{environmentLabel}</span></div><div className="flex min-h-11 items-center gap-3 rounded-lg px-2"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#dce7f6] text-navy"><UserRound size={15} /></span><div className="min-w-0"><p className="truncate text-[11px] font-semibold text-white" title={accountEmail}>{accountEmail}</p><p className="mt-0.5 text-[10px] text-navy-muted">Account</p></div></div></div>
  </aside>;
}
