export const INCIDENT_REPOSITORY = Symbol('INCIDENT_REPOSITORY');
export const ANALYSIS_RUN_REPOSITORY = Symbol('ANALYSIS_RUN_REPOSITORY');
export const EVIDENCE_REPOSITORY = Symbol('EVIDENCE_REPOSITORY');
export const ACTION_REPOSITORY = Symbol('ACTION_REPOSITORY');
export const ALERT_RECEIPT_REPOSITORY = Symbol('ALERT_RECEIPT_REPOSITORY');

export const CREATE_INCIDENT_FROM_ALERT = Symbol('CREATE_INCIDENT_FROM_ALERT');
export const GET_INCIDENT_DETAIL = Symbol('GET_INCIDENT_DETAIL');
